
development:   
  host: 127.0.0.1
  database: mimodb
  autocreate_indexes: true

test:
  host: 127.0.0.1
  database: mimodb_test

# set these environment variables on your prod server
production:
  uri: "mongodb://heroku:120881heroku@staff.mongohq.com:10037/app1611555" 
 