<% if ENV['MONGOHQ_URL'] %>
  <% mongohq = URI.parse(ENV['MONGOHQ_URL']) %>
mongohq:
  host: <%= mongohq.host %>
  port: <%= mongohq.port %>
  database: <%= mongohq.path.sub '/', '' %>
  username: <%= mongohq.user %>
  password: <%= mongohq.password %>
<% end %>

development:
  host: 127.0.0.1
  database: mimodb

test:
  host: 127.0.0.1
  database: mimodb_test

# set these environment variables on your prod server
production:
